#!/usr/bin/env python3
"""Remap SRT timestamps from trimmed audio back to original audio timeline.

Uses silence_map.json (generated by generate_silence_map.py) to translate
timestamps from silence-removed audio back to the original audio's timeline.
The SRT file is modified in-place.

Usage:
    uv run python scripts/remap_srt_timestamps.py <srt_file> <silence_map_json>
"""

import json
import sys
from datetime import timedelta
from pathlib import Path

import srt


def trimmed_to_original(trimmed_seconds: float, kept_segments: list[dict[str, float]]) -> float:
    """Map a trimmed-audio timestamp to the original-audio timestamp.

    Args:
        trimmed_seconds: Timestamp in the trimmed (silence-removed) audio.
        kept_segments: List of segment mappings from silence_map.json.

    Returns:
        Corresponding timestamp in the original audio.
    """
    for seg in kept_segments:
        if seg["trimmed_start"] <= trimmed_seconds <= seg["trimmed_end"]:
            offset = trimmed_seconds - seg["trimmed_start"]
            return seg["original_start"] + offset

    # Beyond last segment: clamp to end of last segment
    if kept_segments:
        last = kept_segments[-1]
        if trimmed_seconds > last["trimmed_end"]:
            return last["original_end"]

    return trimmed_seconds


def main() -> int:
    if len(sys.argv) != 3:
        print(
            f"Usage: {sys.argv[0]} <srt_file> <silence_map_json>",
            file=sys.stderr,
        )
        return 1

    srt_path = Path(sys.argv[1])
    map_path = Path(sys.argv[2])

    if not srt_path.exists():
        print(f"Error: SRT file not found: {srt_path}", file=sys.stderr)
        return 1

    if not map_path.exists():
        print(f"Error: Silence map not found: {map_path}", file=sys.stderr)
        return 1

    with open(map_path) as f:
        silence_map = json.load(f)

    kept_segments = silence_map["kept_segments"]
    if not kept_segments:
        return 0

    srt_content = srt_path.read_text(encoding="utf-8")
    subtitles = list(srt.parse(srt_content))

    for sub in subtitles:
        original_start = trimmed_to_original(sub.start.total_seconds(), kept_segments)
        original_end = trimmed_to_original(sub.end.total_seconds(), kept_segments)
        sub.start = timedelta(seconds=original_start)
        sub.end = timedelta(seconds=original_end)

    srt_path.write_text(srt.compose(subtitles), encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
